"""
answer_validator.py — Validates generated LLM responses for structural grounding and citation consistency.
"""
from __future__ import annotations

import re
from typing import List, Set, Optional, Dict, Any

from app.config import settings
from app.models.rag_answer import RAGAnswer
from app.core.logger import engine_logger


class AnswerValidator:
    """
    Validates generated answers to enforce citation integrity, sanitize invalid citations,
    and detect insufficient context responses.
    """

    CITATION_PATTERN = re.compile(r"\[(SOURCE_\d+)\]")

    INSUFFICIENT_CONTEXT_PATTERNS = [
        re.compile(r"insufficient\s+information", re.IGNORECASE),
        re.compile(r"not\s+enough\s+information", re.IGNORECASE),
        re.compile(r"does\s+not\s+(contain|provide|state|mention)\s+sufficient", re.IGNORECASE),
        re.compile(r"do\s+not\s+(contain|provide|state|mention)\s+sufficient", re.IGNORECASE),
        re.compile(r"no\s+information\s+(is\s+)?provided", re.IGNORECASE),
        re.compile(r"not\s+documented\s+in\s+the\s+provided", re.IGNORECASE),
    ]

    def __init__(self, max_answer_length: Optional[int] = None):
        self.max_answer_length = max_answer_length or settings.RAG_MAX_ANSWER_LENGTH

    def validate(
        self,
        raw_answer: str,
        valid_source_ids: Set[str],
    ) -> RAGAnswer:
        """
        Validate and sanitize raw generated answer text.

        Args:
            raw_answer: Text returned by LLM.
            valid_source_ids: Set of valid source identifiers present in the context.

        Returns:
            RAGAnswer domain object.
        """
        if not raw_answer or not raw_answer.strip():
            return RAGAnswer(
                text="No response was generated by the model.",
                raw_answer=raw_answer or "",
                cited_source_ids=[],
                invalid_source_ids=[],
                is_grounded=False,
                is_insufficient_context=True,
                validation_notes=["Answer text was empty"],
            )

        clean_text = raw_answer.strip()

        # Check for insufficient context indicators
        is_insufficient = any(p.search(clean_text) for p in self.INSUFFICIENT_CONTEXT_PATTERNS)

        # Extract all citations [SOURCE_X]
        extracted_citations = self.CITATION_PATTERN.findall(clean_text)
        unique_cited = sorted(list(dict.fromkeys(extracted_citations)))

        valid_cited: List[str] = []
        invalid_cited: List[str] = []

        for cid in unique_cited:
            if cid in valid_source_ids:
                valid_cited.append(cid)
            else:
                invalid_cited.append(cid)

        sanitized_text = clean_text
        validation_notes: List[str] = []

        # Handle invalid citations safely
        if invalid_cited:
            validation_notes.append(
                f"Model referenced invalid source IDs not in context: {invalid_cited}"
            )
            engine_logger.warning(
                f"AnswerValidator: Invalid citations found: {invalid_cited}. Sanitizing from output."
            )
            for inv_id in invalid_cited:
                # Remove occurrences of [SOURCE_99] from output text
                sanitized_text = re.sub(rf"\[{re.escape(inv_id)}\]", "", sanitized_text)
            # Clean up potential double spaces caused by removed tags
            sanitized_text = re.sub(r" +", " ", sanitized_text).strip()

        # Check response size limit
        if len(sanitized_text) > self.max_answer_length:
            validation_notes.append(
                f"Answer length ({len(sanitized_text)}) exceeds limit ({self.max_answer_length})"
            )
            sanitized_text = sanitized_text[: self.max_answer_length].rstrip() + "..."

        is_grounded = bool(valid_cited) or is_insufficient

        return RAGAnswer(
            text=sanitized_text,
            raw_answer=raw_answer,
            cited_source_ids=valid_cited,
            invalid_source_ids=invalid_cited,
            is_grounded=is_grounded,
            is_insufficient_context=is_insufficient,
            validation_notes=validation_notes,
        )
